// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

// export const awsConfig = {
//   aws_project_region: 'us-east-1',
//   aws_cognito_identity_pool_id:
//     'us-east-1:e7ff8039-eaba-4b54-acde-d2d17edb2dce',
//   aws_cognito_region: 'us-east-1',
//   aws_user_pools_id: 'us-east-1_p7i7U9Clu',
//   aws_user_pools_web_client_id: '1v0vqjidrbik5r3104buph0s7g',
//   oauth: {
//     domain: 'crema-react.auth.us-east-1.amazoncognito.com',
//     scope: [
//       'phone',
//       'email',
//       'openid',
//       'profile',
//       'aws.cognito.signin.user.admin',
//     ],
//     redirectSignIn: 'https://crema-react.firebaseapp.com/',
//     redirectSignOut: 'https://crema-react.firebaseapp.com/',
//     responseType: 'code',
//   },
//   federationTarget: 'COGNITO_USER_POOLS',
// };

// export const awsConfig = {
//   Auth: {
//     mandatorySignIn: false,
//     region: 'us-east-1',
//     userPoolId: 'us-east-1_tBgIbyQyy',
//     identityPoolId: 'us-east-1:ee4b1bce-af0c-483c-91e6-68716e41d87f',
//     userPoolWebClientId: '3ddv3rf5j2brin998ugo1h2kjc',
//   },
//   // Storage: {
//   //     region: process.env.REACT_APP_STORAGE_REGION,
//   //     bucket: process.env.REACT_APP_STORAGE_BUCKET,
//   //     identityPoolId: process.env.REACT_APP_IDENTITY_POOL_ID
//   // },
//   API: {
//     endpoints: [
//       {
//         name: 'tunexo',
//         endpoint: 'https://mz0kzkc4wb.execute-api.us-east-1.amazonaws.com/DEV',
//         region: 'us-east-1',
//       },
//       // {
//       //     name: process.env.REACT_APP_OLD_ENDPOINT_NAME,
//       //     endpoint: process.env.REACT_APP_ENDPOINT_GATEWAY_URL,
//       //     region: process.env.REACT_APP_ENDPOINT_REGION
//       // }
//     ],
//   },
// };

export const awsConfig = {
  Auth: {
    mandatorySignIn: false,
    region: process.env.REACT_APP_REGION,
    userPoolId: process.env.REACT_APP_USERPOOL_ID,
    identityPoolId: process.env.REACT_APP_IDENTITY_POOL_ID,
    userPoolWebClientId: process.env.REACT_APP_APP_CLIENT_ID,
  },
  // Storage: {
  //     region: process.env.REACT_APP_STORAGE_REGION,
  //     bucket: process.env.REACT_APP_STORAGE_BUCKET,
  //     identityPoolId: process.env.REACT_APP_IDENTITY_POOL_ID
  // },
  API: {
    endpoints: [
      {
        name: process.env.REACT_APP_ENDPOINT_NAME,
        endpoint: process.env.REACT_APP_ENDPOINT_GATEWAY_URL,
        region: process.env.REACT_APP_REGION,
      },
      // {
      //     name: process.env.REACT_APP_OLD_ENDPOINT_NAME,
      //     endpoint: process.env.REACT_APP_ENDPOINT_GATEWAY_URL,
      //     region: process.env.REACT_APP_ENDPOINT_REGION
      // }
    ],
  },
};
